INSERT INTO departamentos (COD_DPTO, DESCRIPCION) VALUES
('1', 'AGUIRRE'),
('2', 'ALBERDI'),
('3', 'ATAMISQUI'),
('5', 'BANDA'),
('4', 'AVELLANEDA'),
('6', 'BELGRANO'),
('7', 'CAPITAL'),
('8', 'COPO'),
('9', 'CHOYA'),
('10', 'FIGUEROA'),
('11', 'GRAL.TABOADA'),
('12', 'GUASAYAN'),
('13', 'JIMENEZ'),
('14', 'LORETO'),
('15', 'JUAN FELIPE IBARRA'),
('16', 'MITRE'),
('17', 'MORENO'),
('18', 'OJO DE AGUA'),
('19', 'PELLEGRINI'),
('20', 'QUEBRACHOS'),
('21', 'RIO HONDO'),
('22', 'RIVADAVIA'),
('23', 'ROBLES'),
('24', 'SALAVINA'),
('25', 'SAN MARTIN'),
('26', 'SARMIENTO'),
('27', 'SILIPICA');